---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jamie
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: "jamie-deployment-succeeded"
    notifications.argoproj.io/subscribe.on-health-degraded.grafana: "jamie-degraded"
    notifications.argoproj.io/subscribe.on-sync-failed.grafana: "jamie-sync-failed"
    notifications.argoproj.io/subscribe.on-deployed.grafana: "jamie-deployed"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.grafana: "jamie-status-unknown"
    recipients.argocd-notifications.argoproj.io: "slack:platform-alerts"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: jamie
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  source:
    repoURL: git@github.com:brunovlucena/auto-devops.git
    path: 20-platform/services/jamie/deploy
    targetRevision: HEAD
    helm:
      releaseName: jamie
      valueFiles:
        - values.yaml
        - overlays/local/values-local.yaml
