
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: "redis-deployment-succeeded"
    notifications.argoproj.io/subscribe.on-health-degraded.grafana: "redis-degraded"
    notifications.argoproj.io/subscribe.on-sync-failed.grafana: "redis-sync-failed"
    notifications.argoproj.io/subscribe.on-deployed.grafana: "redis-deployed"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.grafana: "redis-status-unknown"
    recipients.argocd-notifications.argoproj.io: "slack:platform-alerts"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  source:
    repoURL: git@github.com:brunovlucena/auto-devops.git
    path: 20-platform/services/redis/deploy
    targetRevision: HEAD
    helm:
      releaseName: redis
      valueFiles:
        - values.yaml
        - overlays/local/values-local.yaml

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: "mongodb-deployment-succeeded"
    notifications.argoproj.io/subscribe.on-health-degraded.grafana: "mongodb-degraded"
    notifications.argoproj.io/subscribe.on-sync-failed.grafana: "mongodb-sync-failed"
    notifications.argoproj.io/subscribe.on-deployed.grafana: "mongodb-deployed"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.grafana: "mongodb-status-unknown"
    recipients.argocd-notifications.argoproj.io: "slack:platform-alerts"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  source:
    repoURL: git@github.com:brunovlucena/auto-devops.git
    path: 20-platform/services/mongodb/deploy
    targetRevision: HEAD
    helm:
      releaseName: mongodb
      valueFiles:
        - values.yaml
        - overlays/local/values-local.yaml