{
 "title": "Tempo Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uptime [Last 30 Days]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (job) (sum_over_time(up{namespace=\"tempo\"}[30d])) / sum by (job) (count_over_time(up{namespace=\"tempo\"}[30d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Firing", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "CPU Usage (TOTAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"tempo\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"tempo\", resource=\"cpu\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (TOTAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"tempo\", resource=\"memory\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate (inbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"tempo\", direction=\"inbound\"}[5m])) / sum(irate(response_total{namespace=\"tempo\", direction=\"inbound\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate (outbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"tempo\", direction=\"outbound\"}[$__rate_interval])) / sum(irate(response_total{namespace=\"tempo\", direction=\"outbound\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"tempo\", direction=\"inbound\", tls=\"true\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (irate(response_latency_ms_bucket{namespace=\"tempo\", direction=\"inbound\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Trace Rejection Rate SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_traces_rejected_total[1m])) / sum(rate(tempo_ingester_traces_received_total[1m]))",
     "legendFormat": "Rejection Rate"
    }
   ]
  },
  {
   "title": "Span Drop Rate SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_spans_dropped_total[1m])) / sum(rate(tempo_receiver_spans_received_total[1m]))",
     "legendFormat": "Drop Rate"
    }
   ]
  },
  {
   "title": "Request Latency SLO (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tempo_request_duration_seconds_bucket[1m])) by (le)) * 1000",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Search Latency SLO (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tempo_request_duration_seconds_bucket{route=\"querier_api_search\"}[1m])) by (le)) * 1000",
     "legendFormat": "P99 Search Latency"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "TempoDroppedLogLines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(tempo_dropped_log_lines_total[5m])) > 0",
     "legendFormat": "Dropped Log Lines"
    }
   ]
  },
  {
   "title": "TempoDistributorIngesterAppendFailures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_ingester_append_failures_total[5m])) > 0",
     "legendFormat": "Append Failures"
    }
   ]
  },
  {
   "title": "TempoDiscardedSpans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(tempo_discarded_spans_total[5m])) by (reason)",
     "legendFormat": "Discarded Spans - {{reason}}"
    }
   ]
  },
  {
   "title": "TempoIngesterFailedFlushRetries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_flush_failed_retries_total[5m])) > 0",
     "legendFormat": "Failed Flush Retries"
    }
   ]
  },
  {
   "title": "TempoIngesterFailedFlushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_failed_flushes_total[5m])) > 0",
     "legendFormat": "Failed Flushes"
    }
   ]
  },
  {
   "title": "TempoPodsinPendingState",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Pending\", namespace=\"tempo\", pod=~\"tempo-.*\"} == 1",
     "legendFormat": "Pending Pod - {{pod}}"
    }
   ]
  },
  {
   "title": "TempoUnhealthyRingMembers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "tempo_ring_members{state=\"Unhealthy\"} > 0",
     "legendFormat": "Unhealthy Ring Members - {{name}}"
    }
   ]
  },
  {
   "title": "TempoPodRestarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"tempo\", pod=~\"tempo-.*\"} > 5",
     "legendFormat": "Pod Restarts - {{pod}}"
    }
   ]
  },
  { "title": "Additional Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "TempoInstanceDown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "up{job=\"tempo\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TempoDistributorErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_errors_total[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TempoIngesterRejectedTraces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_traces_rejected_total[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TempoDroppedSpans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_spans_dropped_total[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TempoIngestionFailures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_spans_failed_total[5m])) > 0",
     "legendFormat": "Failed Spans Rate"
    }
   ]
  },
  {
   "title": "TempoStorageErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "sum(rate(tempo_storage_errors_total[5m])) by (operation)",
     "legendFormat": "Storage Errors - {{operation}}"
    }
   ]
  },
  {
   "title": "TempoQuerierErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(tempo_querier_errors_total[5m])) by (tenant)",
     "legendFormat": "Querier Errors - {{tenant}}"
    }
   ]
  },
  {
   "title": "TempoCompactorBlockFailures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(tempo_compactor_block_processing_failures_total[15m])) > 0",
     "legendFormat": "Block Processing Failures"
    }
   ]
  },
  {
   "title": "TempoRetentionDeletionFailures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum(rate(tempo_retention_deletion_failures_total[1h])) > 0",
     "legendFormat": "Retention Deletion Failures"
    }
   ]
  },
  {
   "title": "TempoDBRetentionErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_retention_errors_total[15m])) > 0",
     "legendFormat": "DB Retention Errors"
    }
   ]
  },
  {
   "title": "TempoMetricsGeneratorFailedBlockFlushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(rate(tempo_metrics_generator_processor_local_blocks_failed_flushes_total[5m])) > 0",
     "legendFormat": "Failed Block Flushes"
    }
   ]
  },
  {
   "title": "TempoDBCompactionErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_errors_total[15m])) > 10",
     "legendFormat": "DB Compaction Errors"
    }
   ]
  }
 ]
}