---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  # workloads:
  #   - name: eventing-controller
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: eventing-webhook
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: icm-controller
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: icm-dispatcher
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: pingsource-mt-adapter
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: job-sink
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: mt-broker-controller
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: mt-broker-filter
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
  #   - name: mt-broker-ingress
  #     nodeSelector:
  #       knative: "true"
  #     tolerations:
  #       - key: "knative"
  #         operator: "Equal"
  #         value: "true"
  #         effect: "NoSchedule"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-eventing-role
  namespace: knative-eventing
rules:
  - apiGroups:
    - ""
    resources:
    - "events"
    - "namespaces"
    - "*" # TODO: Refactor this
    verbs:
    - create
    - get
    - list
    - watch
    - update
  - apiGroups:
    - "eventing.knative.dev"
    resources:
    - "*"
    verbs:
    - "*"
  - apiGroups:
    - "sources.knative.dev"
    resources:
    - "*"
    verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-eventing-role-binding
  namespace: knative-eventing
subjects:
- kind: ServiceAccount
  name: knative-eventing
  namespace: knative-eventing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-eventing-role
