kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: auto-devops
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0

# Setup Instructions:
# 1. Start local registry:
#    docker run -d --restart=always -p "127.0.0.1:5001:5000" --name "kind-registry" registry:2
#    docker network connect "kind" "kind-registry"
#
# 2. Create cluster:
#    kind create cluster --config kind-config.yaml
#
# 3. Install Knative Serving (your installation method)
#
# 4. Apply registry patch for Knative:
#    kubectl apply -f knative-registry-patch.yaml
#    kubectl rollout restart deployment/controller -n knative-serving
#
# This fixes the issue where Knative can't pull images from localhost:5001
# by skipping tag resolution and using containerd registry mirrors.