{
 "title": "Alloy Alerts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime [Last 30 Days]",
   "type": "timeseries",
   "description": "Percentage of time Loki has been available over the last 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (job) (sum_over_time(up{namespace=\"loki\"}[30d])) / sum by (job) (count_over_time(up{namespace=\"loki\"}[30d]))) * 100",
     "legendFormat": "Uptime"
    }
   ]
  },
  { "title": "Firing", "type": "alertlist", "description": "Current firing alerts for Loki", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "CPU Usage (TOTAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"loki\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"loki\", resource=\"cpu\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"loki\", resource=\"cpu\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (TOTAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"loki\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"loki\", resource=\"memory\"}\n) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"loki\", resource=\"memory\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate (inbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"alloy\", direction=\"inbound\"}[5m])) / sum(irate(response_total{namespace=\"alloy\", direction=\"inbound\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate (outbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"alloy\", direction=\"outbound\"}[$__rate_interval])) / sum(irate(response_total{namespace=\"alloy\", direction=\"outbound\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"alloy\", direction=\"inbound\", tls=\"true\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (irate(response_latency_ms_bucket{namespace=\"alloy\", direction=\"inbound\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "AlloyIngestionSLOViolation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(alloy:ingestion:error_ratio[24h]) > 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AlloyIngestionErrorBudgetBurn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "alloy:ingestion:error_ratio > 0.001 and alloy:ingestion:error_ratio > (0.001 * 14.4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AlloyQueryErrorBudgetBurn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "alloy:query:error_ratio > 0.01 and alloy:query:error_ratio > (0.01 * 14.4)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "AlloyInstanceDown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "up{job=\"alloy\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AlloyDistributorErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(alloy_distributor_errors_total[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AlloyQueryQueueSaturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "alloy_query_frontend_queue_length / alloy_query_frontend_queue_capacity > 0.8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}