# Default values for curly-service
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ghcr.io/brunovlucena/curly-service
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: curly-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

# Environment variables
env:
  - name: PORT
    value: "8082"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector:14268/api/traces"

# Service Monitor for Prometheus
serviceMonitor:
  enabled: true
  labels: {}
  interval: 30s
  path: /metrics

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi 