apiVersion: v1
kind: Secret
metadata:
  name: jamie-secrets
  labels:
    {{- include "jamie.labels" . | nindent 4 }}
type: Opaque
data:
  # Google API key for Gemini (base64 encoded)
  # Set this value using: echo -n "your-api-key" | base64
  google-api-key: {{ .Values.jamie.secrets.googleApiKey | b64enc | quote }} 