apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
---
# RabbitMQ
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  namespace: rabbitmq
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: rabbitmq.local
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-management
            port:
              number: 15672
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 5672
---
# Grafana
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
---
# Jamie
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jamie
  namespace: jamie
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: jamie.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jamie
            port:
              number: 80