# Default values for moe-service
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ghcr.io/brunovlucena/moe-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: moe-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

# Environment variables
env:
  - name: PORT
    value: "8080"
  - name: JAEGER_ENDPOINT
    value: "http://tempo-distributor.tempo:3100"
  - name: LARRY_SERVICE_URL
    value: "http://larry-service:8081"

# Service Monitor for Prometheus
serviceMonitor:
  enabled: true
  labels: {}
  interval: 30s
  path: /metrics

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi 