---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-credentials
  type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: test-user-credentials
type: Opaque
stringData:
  username: test
  password: test