--- 
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin-secret
  namespace: knative-operator
type: Opaque
stringData:
  uri: rabbitmq-cluster.rabbitmq.svc.cluster.local
  port: "5672"
  username: admin
  password: admin
--- 
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin-secret
  namespace: rabbitmq
type: Opaque
stringData:
  uri: rabbitmq-cluster.rabbitmq.svc.cluster.local
  port: "5672"
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-notifi-secret
  namespace: rabbitmq
type: Opaque
stringData:
  uri: rabbitmq-cluster.rabbitmq.svc.cluster.local
  host: rabbitmq-cluster.rabbitmq.svc.cluster.local
  port: "5672"
  username: notifi
  password: notifi
---
