{{- if and .Values.ollama.enabled .Values.ollama.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jamie.ollama.fullname" . }}-pvc
  labels:
    {{- include "jamie.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
  {{- if .Values.ollama.persistence.storageClass }}
  {{- if (eq "-" .Values.ollama.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.ollama.persistence.storageClass }}"
  {{- end }}
  {{- end }}
---
{{- end }}