apiVersion: v1
kind: Service
metadata:
  name: {{ include "jamie.fullname" . }}
  labels:
    {{- include "jamie.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- if .Values.monitoring.serviceMonitor.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.jamie.service.port }}"
    prometheus.io/path: "{{ .Values.jamie.config.observability.metrics.path }}"
  {{- end }}
spec:
  type: {{ .Values.jamie.service.type }}
  ports:
    - port: {{ .Values.jamie.service.port }}
      targetPort: {{ .Values.jamie.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jamie.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api 