# Alternative approach using trust-manager
# Only use this if you have trust-manager installed
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots-bundle
  namespace: {{ .Release.Namespace }}
spec:
  sources:
  # Include the CA certificate from our self-signed issuer
  - secret:
      name: "linkerd-identity-issuer"
      key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
    namespaceSelector:
      matchLabels:
        name: {{ .Release.Namespace }}
    selector:
      matchLabels:
        linkerd.io/control-plane-component: identity 