apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer-tls
spec:
  secretName: linkerd-identity-issuer-tls # This is the secret that will be created
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  issuerRef:
    name: linkerd-self-signed-issuer # Reference the Issuer/ClusterIssuer you created
    kind: Issuer
  commonName: identity.linkerd.cluster.local # This is crucial for Linkerd
  isCA: true # This certificate will be used to sign other certificates
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
    - cert sign

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
spec:
  secretName: linkerd-proxy-injector
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: Issuer
  commonName: linkerd-proxy-injector
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
spec:
  secretName: linkerd-sp-validator
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: Issuer
  commonName: linkerd-sp-validator
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
spec:
  secretName: linkerd-policy-validator
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: Issuer
  commonName: linkerd-policy-validator