apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  secretName: linkerd-trust-anchor
  duration: 17520h # 2 years
  renewBefore: 8760h # 1 year
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: root.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  issuerRef:
    name: linkerd-ca-issuer
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc.cluster.local
  - linkerd-proxy-injector.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-sp-validator.linkerd.svc.cluster.local
  - linkerd-sp-validator.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-policy-validator.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-policy-validator.linkerd.svc.cluster.local
  - linkerd-policy-validator.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-jaeger-webhook
  namespace: linkerd
spec:
  secretName: linkerd-jaeger-webhook-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-jaeger-webhook.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-jaeger-webhook.linkerd.svc.cluster.local
  - linkerd-jaeger-webhook.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: linkerd
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBizCCATCgAwIBAgIQUGVCWrA6qKhS2NGlqiHaCDAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNTA2MDUyMzE2
    MzNaFw0yNzA2MDUyMzE2MzNaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmQG3GF/z4lbSDcwD
    nTgfDnDniacqjjZk1mPXLQIRPeaPjiU1Amyxoeofz/bYbKI+meFL4LoFrYjQDomG
    wblRPKNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFIVQvGDh+iy5riUvQEnvqhpfwE+iMAoGCCqGSM49BAMCA0kAMEYCIQDU8eYi
    Vnz5oiKjc7fO7/X0RIcLwDw8VGRmO9he9XqG0wIhAIikNzAO4P5Tf4v8GMitKlIl
    Hg2yIKE0JPDZIdaKpMB/
    -----END CERTIFICATE-----