apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  secretName: linkerd-trust-anchor
  duration: 17520h # 2 years
  renewBefore: 8760h # 1 year
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: root.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  issuerRef:
    name: linkerd-ca-issuer
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc.cluster.local
  - linkerd-proxy-injector.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-sp-validator.linkerd.svc.cluster.local
  - linkerd-sp-validator.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-policy-validator.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-policy-validator.linkerd.svc.cluster.local
  - linkerd-policy-validator.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-jaeger-webhook
  namespace: linkerd
spec:
  secretName: linkerd-jaeger-webhook-k8s-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: Issuer
  commonName: linkerd-jaeger-webhook.linkerd.svc.cluster.local
  dnsNames:
  - linkerd-jaeger-webhook.linkerd.svc.cluster.local
  - linkerd-jaeger-webhook.linkerd.svc
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: linkerd
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBjDCCATGgAwIBAgIRAPUtNeNgGsOssLzB1+uBfpMwCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwNjA1MjMy
    OTEzWhcNMjcwNjA1MjMyOTEzWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
    c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAZxuZCmn0buKLHk
    AUDChj0GxyzTtJsEPl+FoyjFfcbdLd0Zek3z0bNFcRQ2Php0pEErwwr26Vef4FqE
    1cuSDACjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
    DgQWBBQrsBVEL8HcKTEPssvDpT3pz8pGYzAKBggqhkjOPQQDAgNJADBGAiEA9Vo0
    yF2DxW5aR9WjZrt1V7IZUWAxsradylItzmpbTPsCIQDTueShahPzd3qOHbKsGOIk
    dZ89EYHSmnOYe36e72E3OQ==
    -----END CERTIFICATE-----