apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-self-signed-issuer
  namespace: linkerd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-ca-issuer
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor