apiVersion: v2
name: istio
description: A Helm chart for deploying Istio

type: application

version: 0.1.0

appVersion: "1.26.1"

dependencies:
  - name: base
    version: 1.26.1
    repository: https://istio-release.storage.googleapis.com/charts 
  - name: istiod
    version: 1.26.1
    repository: https://istio-release.storage.googleapis.com/charts 
  - name: istio-ingress
    version: 1.26.1
    repository: https://istio-release.storage.googleapis.com/charts 