apiVersion: v2
name: alloy
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.12.1"

dependencies:
  - name: cert-manager
    version: 1.5.0
    repository: https://github.com/cert-manager/cert-manager