apiVersion: v1
kind: Secret
metadata:
  name: auto-devops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:brunovlucena/auto-devops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # TODO: ADD YOUR KEY. DO not Commit
    -----END OPENSSH PRIVATE KEY-----

# TODO: Use Sealed Secrets to store the private key
