apiVersion: v1
kind: Secret
metadata:
  name: auto-devops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:brunovlucena/auto-devops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCmMhneG4ImBW0kJbeMbysVqU0Fs0DTF0/wFd3jOVsChAAAAKCyOUo2sjlK
    NgAAAAtzc2gtZWQyNTUxOQAAACCmMhneG4ImBW0kJbeMbysVqU0Fs0DTF0/wFd3jOVsChA
    AAAEASTef5gz7/P6V+rq3jg9lMz4Ihl9lcfwFT95GN4D1v5qYyGd4bgiYFbSQlt4xvKxWp
    TQWzQNMXT/AV3eM5WwKEAAAAF2JydW5vbHVjZW5hQG1hYy0yLmxvY2FsAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
  knownHosts: |
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8LGDX9Z5e0mKO4J0I2Gex+4N/6JDZ0lQVaZOGAA+JVjH8JoCJ8HMTVbhWPh0tCCWW6PW+N/WU6tT6K9aNQcP6KuI+kKl4JqJhW7g1j3P3KxO9BU5sFg3K8A+T+N4k7N3v+Cq5Y0A6M9N5Y5zS3g2BXzY8l5G4LoQE0Zo+tWYlZKH8nz6l0m4N6Hy8G9q4N6F9H8Y5e1dF4jQKcXnM5L5K9A9FmwN+Y8o4nJ5g+zw==
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl 

# TODO: Use Sealed Secrets to store the private key